class Persona
{
	//Atributos
	int edad=20; //Estas variables cn atributos son inicializadasa 0, si no se inicializan explicitamente
	float estatura=1.7f;
	String nombre="Susino";//La calse String se utiliza para el manejo de cadenas

	//Metodos
	//Cuando se declara un metodo, se tiene que implementar (implementacion "inline")
	//El estilo tipico de nomenclatura en Java es comenzar el nombre del metodo con minuscula, y las
	//palabras siguientes comienzan con Mayuscula
	void saludar(){

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");

		System.out.println("Hola soy "+nombre+", y tengo "+edad+" mido "+estatura+" ");
	}
}